// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
	"time"
)

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID        int64   `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name      string  `gorm:"column:name;type:varchar(50);not null;comment:分类名称" json:"name"`                     // 分类名称
	CreatedAt *string `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`                     // 创建时间
	UpdatedAt *string `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                     // 更新时间
	DeletedAt *string `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                     // 删除时间
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}

// BeforeCreate 创建之前
func (s *Category) BeforeCreate(tx *gorm.DB) (err error) {
	if s.CreatedAt == nil {
		createdAt := time.Now().Format("2006-01-02 15:04:05")
		s.CreatedAt = &createdAt
	}

	if s.UpdatedAt == nil {
		updatedAt := time.Now().Format("2006-01-02 15:04:05")
		s.UpdatedAt = &updatedAt
	}

	return
}

// BeforeUpdate 更新之前
func (s *Category) BeforeUpdate(tx *gorm.DB) (err error) {
	if s.UpdatedAt == nil {
		updatedAt := time.Now().Format("2006-01-02 15:04:05")
		s.UpdatedAt = &updatedAt
	}

	return
}

// AfterFind 查询之后
func (s *Category) AfterFind(tx *gorm.DB) (err error) {
	if s.CreatedAt != nil {
		createdAt := time.Now().Format("2006-01-02 15:04:05")
		s.CreatedAt = &createdAt
	}

	if s.UpdatedAt != nil {
		updatedAt := time.Now().Format("2006-01-02 15:04:05")
		s.UpdatedAt = &updatedAt
	}

	if s.DeletedAt != nil {
		deletedAt := time.Now().Format("2006-01-02 15:04:05")
		s.DeletedAt = &deletedAt
	}

	return
}

// BeforeDelete 删除之前
func (s *Category) BeforeDelete(tx *gorm.DB) (err error) {
	if s.DeletedAt == nil {
		deletedAt := time.Now().Format("2006-01-02 15:04:05")
		s.DeletedAt = &deletedAt
	}

	return
}
