// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
	"time"
)

const TableNameMenu = "menu"

// Menu 菜单表
type Menu struct {
	ID             int64           `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"`               // ID
	Pid            int64           `gorm:"column:pid;type:int(10) unsigned;not null;comment:父级id" json:"pid"`                                // 父级id
	Title          string          `gorm:"column:title;type:varchar(50);not null;comment:菜单名称" json:"title"`                                 // 菜单名称
	Name           string          `gorm:"column:name;type:varchar(50);not null;comment:路由名称" json:"name"`                                   // 路由名称
	Path           string          `gorm:"column:path;type:varchar(50);not null;comment:路由路径" json:"path"`                                   // 路由路径
	Redirect       string          `gorm:"column:redirect;type:varchar(50);not null;comment:重定向" json:"redirect"`                            // 重定向
	Icon           string          `gorm:"column:icon;type:varchar(50);not null;comment:菜单图标" json:"icon"`                                   // 菜单图标
	ComponentAlias string          `gorm:"column:component_alias;type:varchar(100);not null;comment:组件路径" json:"component_alias"`            // 组件路径
	IsLink         string          `gorm:"column:is_link;type:varchar(255);not null;comment:链接地址" json:"is_link"`                            // 链接地址
	IsHide         int64           `gorm:"column:is_hide;type:tinyint(3) unsigned;not null;default:1;comment:是否隐藏 1=显示 2=隐藏" json:"is_hide"` // 是否隐藏 1=显示 2=隐藏
	Status         int64           `gorm:"column:status;type:tinyint(3) unsigned;not null;default:1;comment:状态 1=启用 2=停用" json:"status"`     // 状态 1=启用 2=停用
	Sort           int64           `gorm:"column:sort;type:int(10) unsigned;not null;comment:排序" json:"sort"`                                // 排序
	MenuAction     []*MenuAction   `json:"menu_action" gorm:"foreignkey:menu_id;references:id" comment:"菜单方法"`                               // 菜单方法
	CreatedAt      *JsonTime       `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`                                   // 创建时间
	UpdatedAt      *JsonTime       `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                                   // 更新时间
	DeletedAt      *gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                   // 删除时间
}

type MenuQuery struct {
	ID             int64         `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"`               // ID
	Pid            int64         `gorm:"column:pid;type:int(10) unsigned;not null;comment:父级id" json:"pid"`                                // 父级id
	Title          string        `gorm:"column:title;type:varchar(50);not null;comment:菜单名称" json:"title"`                                 // 菜单名称
	Name           string        `gorm:"column:name;type:varchar(50);not null;comment:路由名称" json:"name"`                                   // 路由名称
	Path           string        `gorm:"column:path;type:varchar(50);not null;comment:路由路径" json:"path"`                                   // 路由路径
	Redirect       string        `gorm:"column:redirect;type:varchar(50);not null;comment:重定向" json:"redirect"`                            // 重定向
	Icon           string        `gorm:"column:icon;type:varchar(50);not null;comment:菜单图标" json:"icon"`                                   // 菜单图标
	ComponentAlias string        `gorm:"column:component_alias;type:varchar(100);not null;comment:组件路径" json:"component_alias"`            // 组件路径
	IsLink         string        `gorm:"column:is_link;type:varchar(255);not null;comment:链接地址" json:"is_link"`                            // 链接地址
	IsHide         int64         `gorm:"column:is_hide;type:tinyint(3) unsigned;not null;default:1;comment:是否隐藏 1=显示 2=隐藏" json:"is_hide"` // 是否隐藏 1=显示 2=隐藏
	Status         int64         `gorm:"column:status;type:tinyint(3) unsigned;not null;default:1;comment:状态 1=启用 2=停用" json:"status"`     // 状态 1=启用 2=停用
	Sort           int64         `gorm:"column:sort;type:int(10) unsigned;not null;comment:排序" json:"sort"`                                // 排序
	MenuAction     []*MenuAction `json:"menu_action" gorm:"foreignkey:menu_id;references:id" comment:"菜单方法"`                               // 菜单方法
	Children       []MenuQuery   `json:"children" gorm:"-"`
	CreatedAt      *JsonTime     `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt      *JsonTime     `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}

// BeforeCreate 创建之前
func (s *Menu) BeforeCreate(tx *gorm.DB) (err error) {
	now := JsonTime(time.Now())
	s.CreatedAt = &now
	s.UpdatedAt = &now
	return nil
}

// BeforeUpdate 更新之前
func (s *Menu) BeforeUpdate(tx *gorm.DB) (err error) {
	now := JsonTime(time.Now())
	s.UpdatedAt = &now
	return nil
}
