// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
	"time"
)

const TableNameRoleActions = "role_actions"

// RoleActions 角色功能表
type RoleActions struct {
	ID        int64           `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	RoleID    int64           `gorm:"column:role_id;type:int(10) unsigned;not null;comment:角色id" json:"roleId"`           // 角色id
	ActionID  int64           `gorm:"column:action_id;type:int(10) unsigned;not null;comment:功能id" json:"actionId"`       // 功能id
	Name      string          `gorm:"column:name;type:varchar(30);not null;comment:功能名称" json:"name"`                     // 功能名称
	CreatedAt *JsonTime       `gorm:"column:created_at;type:datetime;comment:创建时间" json:"createdAt"`                      // 创建时间
	UpdatedAt *JsonTime       `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updatedAt"`                      // 更新时间
	DeletedAt *gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deletedAt"`                      // 删除时间
}

// TableName RoleActions's table name
func (*RoleActions) TableName() string {
	return TableNameRoleActions
}

// BeforeCreate 创建之前
func (s *RoleActions) BeforeCreate(tx *gorm.DB) (err error) {
	now := JsonTime(time.Now())
	s.CreatedAt = &now
	s.UpdatedAt = &now
	return nil
}

// BeforeUpdate 更新之前
func (s *RoleActions) BeforeUpdate(tx *gorm.DB) (err error) {
	now := JsonTime(time.Now())
	s.UpdatedAt = &now
	return nil
}
