# Config for air
root = "."
tmp_dir = "tmp"                   # Temp dir for .air files (default "tmp")
bin = "tmp/main"                  # Binary file where your main.go compiled to

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  include_ext = ["go", "tmp" "tmpl"]    # Files to watch
  exclude_dir = ["vendor", "web", "common\\extend\\i18n\\locales", "storage"] # Excluded directories
  exclude_regex = ["_test.go"] # Excluded files

[log]
  skip_dir = ["assets"]           # Directories to skip printing logs