# 环境配置
env:
  mode: debug # 运行环境模式 debug, test, release
  port: 8080 # 服务端口
# 日志配置
log:
  max-size: 10 # 单个日志文件大小（MB）
  max-backups: 3  # 最多保留的旧日志文件数
  max-day: 28 # 保留的最大天数
# 数据库配置
mysql:
  host: "root:root@tcp(127.0.0.1:3306)/gin?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  # host: "username:password@tcp(127.0.0.1:3306)/databaseName?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  # 慢查询的时间(ms) 超过这个时间会记录到日志中
  slow-query-seconds: 3s
# Jwt
jwt:
  key: 123456789!@# # 加解密秘钥key
  exp: 7200 # 过期时间（单位秒）
# 跨域
cors:
  allow-origin: "*" # 允许访问的域名列表
  allow-headers: "*" # 允许的请求头列表
  expose-headers: "*" # 允许返回的响应头列表
  allow-methods: GET, POST, PUT, DELETE, OPTIONS # 允许的请求方法列表
  allow-credentials: "true" # 是否允许发送cookie
# 缓存
cache:
  type: "memory"  # memory 或者 "redis"
  redis:
    address: "127.0.0.1:6379"
    password: ""  # 密码为空则不需要
    db: 1


